### PR TITLE
qemu: change fence poll time by current workload

### PR DESCRIPTION
**Pull request by kanlihu**
This will improve performance while waiting the fence in 3D renderering

Tracked-On: OAM-95756
Signed-off-by: Kanli Hu <kanlix.hu@intel.com>

### CODE REVIEW

**Comment by YadongQi** [comment]
Sorry, any differences with https://github.com/projectceladon/vm_manager/pull/63 ?

**Review by feijiang1 — APPROVED** [review]

**Review by feijiang1 — APPROVED** [review]

**Comment by renchenglei** [comment]
@YadongQi
Could you help take a review of this changes? As we updated the commit info to add Jira ID, :) Thanks a lot!

**Comment by YadongQi** [comment]
> @YadongQi
> Could you help take a review of this changes? As we updated the commit info to add Jira ID, :) Thanks a lot!

Could you just amend #63 ? or could you close #63 first?

**Review by feijiang1 — APPROVED** [review]

**Comment by renchenglei** [comment]
> > @YadongQi
> > Could you help take a review of this changes? As we updated the commit info to add Jira ID, :) Thanks a lot!
> 
> Could you just amend #63 ? or could you close #63 first?

@YadongQi, kanli just rename the qemu patch name. :) 
@kanlihu, please close pr63, and update pr next time instead of create a new pr for the same work. Create one new pr, will cause confusion. Thanks a lot.

**Comment by kanlihu** [comment]
I have closed pr63

**Review by YadongQi — APPROVED** [review]

**Pull request merged**
