### PR TITLE
Switch SW device from QXL to RAMFB

### PR DESCRIPTION
**Pull request by renchenglei**
Switch SW rendering device from QXL to RAMFB to
fix the black screen issue.

Tracked-On: OAM-93101
Signed-off-by: Ren Chenglei <chenglei.ren@intel.com>

### CODE REVIEW

**Comment by renchenglei** [comment]
@feijiang1, could you help take a review of this changes? thanks a lot!

**Review by feijiang1 — APPROVED** [review]

**Review by YadongQi — COMMENTED** [review]
1 question: QXL will be abondoned for CiV?

**Comment by renchenglei** [comment]
> 1 question: QXL will be abondoned for CiV?

Yes, on Android R, CIV SW rendering can't launch with QXL, the screen is black.

**Review by YadongQi — APPROVED** [review]

**Comment by YadongQi** [comment]
> > 1 question: QXL will be abondoned for CiV?
> 
> Yes, on Android R, CIV SW rendering can't launch with QXL, the screen is black.

OK, please go forward for integration.

**Comment by renchenglei** [comment]
Sure, Thanks a lot!

**Review by sgnanase — APPROVED** [review]

**Pull request merged**
