### PR TITLE
updated GUEST_CPU_NUM in start_civ.sh

### PR DESCRIPTION
**Pull request by neerajso**
Updated GUEST_CPU_NUM in start_civ.sh. 

Tracked-On: OAM-95320
Signed-off-by: Neeraj Solanki <neeraj.solanki@intel.com>

### CODE REVIEW

**Review by YadongQi — CHANGES_REQUESTED** [review]
Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"

**Comment by neerajso** [comment]
> Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"

Hi Yadong,
Thanks for your comment.
In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
Yes, we modified only default value and user can set value with command argument as well.

**Comment by YadongQi** [comment]
> > Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"
> 
> Hi Yadong,
> Thanks for your comment.
> In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
> We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
> After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
> Yes, we modified only default value and user can set value with command argument as well.

Thanks.  is there any performance difference between "-smp 6" and "-smp 6,cores=3,threads=2,sockets=1"?

**Comment by neerajso** [comment]
> > > Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"
> > 
> > 
> > Hi Yadong,
> > Thanks for your comment.
> > In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
> > We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
> > After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
> > Yes, we modified only default value and user can set value with command argument as well.
> 
> Thanks. is there any performance difference between "-smp 6" and "-smp 6,cores=3,threads=2,sockets=1"?

I followed below link for smp configuration.
    https://manpages.debian.org/testing/qemu-system-x86/qemu-system-x86_64.1.en.html

As such, I checked with "-smp 6,cores=3,threads=2,sockets=1" and "-smp cores=3,threads=2".
The “/proc/cpuinfo” shows same number of logical cores for both above configurations.
And, Geekbench score was same.

**Comment by YadongQi** [comment]
> > > > Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"
> > > 
> > > 
> > > Hi Yadong,
> > > Thanks for your comment.
> > > In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
> > > We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
> > > After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
> > > Yes, we modified only default value and user can set value with command argument as well.
> > 
> > 
> > Thanks. is there any performance difference between "-smp 6" and "-smp 6,cores=3,threads=2,sockets=1"?
> 
> I followed below link for smp configuration.
> https://manpages.debian.org/testing/qemu-system-x86/qemu-system-x86_64.1.en.html
> 
> As such, I checked with "-smp 6,cores=3,threads=2,sockets=1" and "-smp cores=3,threads=2".
> The “/proc/cpuinfo” shows same number of logical cores for both above configurations.
> And, Geekbench score was same.

Since it is virtual cpu, so I think no need to specify cores/threads. Please just use "-smp 6".  And this config is special for CML-S, maybe "-smp 2" is better as the script is for general case.

**Comment by neerajso** [comment]
> > > > > Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"
> > > > 
> > > > 
> > > > Hi Yadong,
> > > > Thanks for your comment.
> > > > In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
> > > > We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
> > > > After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
> > > > Yes, we modified only default value and user can set value with command argument as well.
> > > 
> > > 
> > > Thanks. is there any performance difference between "-smp 6" and "-smp 6,cores=3,threads=2,sockets=1"?
> > 
> > 
> > I followed below link for smp configuration.
> > https://manpages.debian.org/testing/qemu-system-x86/qemu-system-x86_64.1.en.html
> > As such, I checked with "-smp 6,cores=3,threads=2,sockets=1" and "-smp cores=3,threads=2".
> > The “/proc/cpuinfo” shows same number of logical cores for both above configurations.
> > And, Geekbench score was same.
> 
> Since it is virtual cpu, so I think no need to specify cores/threads. Please just use "-smp 6". And this config is special for CML-S, maybe "-smp 2" is better as the script is for general case.

"smp" total value stands for total logical cores which is output of "cores * threads * sockets".
"cores" with smp means physical cores and "threads" with smp means hardware threads.
I went through few links. Specifying "cores" and "threads" avoid any confusion and is recommended for better performance.
We checked on CML-U as well. Performance is scaling more till 6 cores.

**Comment by YadongQi** [comment]
> > > > > > Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"
> > > > > 
> > > > > 
> > > > > Hi Yadong,
> > > > > Thanks for your comment.
> > > > > In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
> > > > > We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
> > > > > After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
> > > > > Yes, we modified only default value and user can set value with command argument as well.
> > > > 
> > > > 
> > > > Thanks. is there any performance difference between "-smp 6" and "-smp 6,cores=3,threads=2,sockets=1"?
> > > 
> > > 
> > > I followed below link for smp configuration.
> > > https://manpages.debian.org/testing/qemu-system-x86/qemu-system-x86_64.1.en.html
> > > As such, I checked with "-smp 6,cores=3,threads=2,sockets=1" and "-smp cores=3,threads=2".
> > > The “/proc/cpuinfo” shows same number of logical cores for both above configurations.
> > > And, Geekbench score was same.
> > 
> > 
> > Since it is virtual cpu, so I think no need to specify cores/threads. Please just use "-smp 6". And this config is special for CML-S, maybe "-smp 2" is better as the script is for general case.
> 
> "smp" total value stands for total logical cores which is output of "cores * threads * sockets".
> "cores" with smp means physical cores and "threads" with smp means hardware threads.
> I went through few links. Specifying "cores" and "threads" avoid any confusion and is recommended for better performance.
> We checked on CML-U as well. Performance is scaling more till 6 cores.
Do you have any data to prove config with "cores" and "threads" would gain better performance than just config "-smp 6"?

**Comment by neerajso** [comment]
> > > > > > > Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"
> > > > > > 
> > > > > > 
> > > > > > Hi Yadong,
> > > > > > Thanks for your comment.
> > > > > > In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
> > > > > > We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
> > > > > > After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
> > > > > > Yes, we modified only default value and user can set value with command argument as well.
> > > > > 
> > > > > 
> > > > > Thanks. is there any performance difference between "-smp 6" and "-smp 6,cores=3,threads=2,sockets=1"?
> > > > 
> > > > 
> > > > I followed below link for smp configuration.
> > > > https://manpages.debian.org/testing/qemu-system-x86/qemu-system-x86_64.1.en.html
> > > > As such, I checked with "-smp 6,cores=3,threads=2,sockets=1" and "-smp cores=3,threads=2".
> > > > The “/proc/cpuinfo” shows same number of logical cores for both above configurations.
> > > > And, Geekbench score was same.
> > > 
> > > 
> > > Since it is virtual cpu, so I think no need to specify cores/threads. Please just use "-smp 6". And this config is special for CML-S, maybe "-smp 2" is better as the script is for general case.
> > 
> > 
> > "smp" total value stands for total logical cores which is output of "cores * threads * sockets".
> > "cores" with smp means physical cores and "threads" with smp means hardware threads.
> > I went through few links. Specifying "cores" and "threads" avoid any confusion and is recommended for better performance.
> > We checked on CML-U as well. Performance is scaling more till 6 cores.
> > Do you have any data to prove config with "cores" and "threads" would gain better performance than just config "-smp 6"?

Below links discuss about mentioning "threads" and "cores" with "smp" with hyper threaded cores.
https://lists.gnu.org/archive/html/qemu-discuss/2014-12/msg00037.html
https://topic.alibabacloud.com/a/kvm-virtualization-smp-symmetric-multi-processor-introduction-and-configuration_8_8_31256740.html

**Comment by YadongQi** [comment]
> > > > > > > > Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"
> > > > > > > 
> > > > > > > 
> > > > > > > Hi Yadong,
> > > > > > > Thanks for your comment.
> > > > > > > In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
> > > > > > > We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
> > > > > > > After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
> > > > > > > Yes, we modified only default value and user can set value with command argument as well.
> > > > > > 
> > > > > > 
> > > > > > Thanks. is there any performance difference between "-smp 6" and "-smp 6,cores=3,threads=2,sockets=1"?
> > > > > 
> > > > > 
> > > > > I followed below link for smp configuration.
> > > > > https://manpages.debian.org/testing/qemu-system-x86/qemu-system-x86_64.1.en.html
> > > > > As such, I checked with "-smp 6,cores=3,threads=2,sockets=1" and "-smp cores=3,threads=2".
> > > > > The “/proc/cpuinfo” shows same number of logical cores for both above configurations.
> > > > > And, Geekbench score was same.
> > > > 
> > > > 
> > > > Since it is virtual cpu, so I think no need to specify cores/threads. Please just use "-smp 6". And this config is special for CML-S, maybe "-smp 2" is better as the script is for general case.
> > > 
> > > 
> > > "smp" total value stands for total logical cores which is output of "cores * threads * sockets".
> > > "cores" with smp means physical cores and "threads" with smp means hardware threads.
> > > I went through few links. Specifying "cores" and "threads" avoid any confusion and is recommended for better performance.
> > > We checked on CML-U as well. Performance is scaling more till 6 cores.
> > > Do you have any data to prove config with "cores" and "threads" would gain better performance than just config "-smp 6"?
> 
> Below links discuss about mentioning "threads" and "cores" with "smp" with hyper threaded cores.
> https://lists.gnu.org/archive/html/qemu-discuss/2014-12/msg00037.html
> https://topic.alibabacloud.com/a/kvm-virtualization-smp-symmetric-multi-processor-introduction-and-configuration_8_8_31256740.html

Cannot find any evidence from these two articals to prove "threads" adn "cores" could improve performances.

**Comment by neerajso** [comment]
> > > > > > > > > Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Hi Yadong,
> > > > > > > > Thanks for your comment.
> > > > > > > > In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
> > > > > > > > We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
> > > > > > > > After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
> > > > > > > > Yes, we modified only default value and user can set value with command argument as well.
> > > > > > > 
> > > > > > > 
> > > > > > > Thanks. is there any performance difference between "-smp 6" and "-smp 6,cores=3,threads=2,sockets=1"?
> > > > > > 
> > > > > > 
> > > > > > I followed below link for smp configuration.
> > > > > > https://manpages.debian.org/testing/qemu-system-x86/qemu-system-x86_64.1.en.html
> > > > > > As such, I checked with "-smp 6,cores=3,threads=2,sockets=1" and "-smp cores=3,threads=2".
> > > > > > The “/proc/cpuinfo” shows same number of logical cores for both above configurations.
> > > > > > And, Geekbench score was same.
> > > > > 
> > > > > 
> > > > > Since it is virtual cpu, so I think no need to specify cores/threads. Please just use "-smp 6". And this config is special for CML-S, maybe "-smp 2" is better as the script is for general case.
> > > > 
> > > > 
> > > > "smp" total value stands for total logical cores which is output of "cores * threads * sockets".
> > > > "cores" with smp means physical cores and "threads" with smp means hardware threads.
> > > > I went through few links. Specifying "cores" and "threads" avoid any confusion and is recommended for better performance.
> > > > We checked on CML-U as well. Performance is scaling more till 6 cores.
> > > > Do you have any data to prove config with "cores" and "threads" would gain better performance than just config "-smp 6"?
> > 
> > 
> > Below links discuss about mentioning "threads" and "cores" with "smp" with hyper threaded cores.
> > https://lists.gnu.org/archive/html/qemu-discuss/2014-12/msg00037.html
> > https://topic.alibabacloud.com/a/kvm-virtualization-smp-symmetric-multi-processor-introduction-and-configuration_8_8_31256740.html
> 
> Cannot find any evidence from these two articals to prove "threads" adn "cores" could improve performances.

As per one link (discussion in qemu community), do not specify HT in the guest, unless you have HT in
the host. We have HT enabled with CML target, hence I specified "threads=2" with smp. 
I checked the GeekBench performance with "-smp 6" on CML-S target (with WW44).
The multi-core score with "-smp 6" is almost half of multi-score with "-smp 6,cores=3,threads=2,sockets=1".

I was not expecting that much difference. 
So, I rechecked again with "-smp 6,cores=3,threads=2,sockets=1" with same environment.
The multi-core score with "-smp 6,cores=3,threads=2,sockets=1" is same as earlier.

**Comment by YadongQi** [comment]
> > > > > > > > > > Any background for this change? And your change might be overwritten when user specify "start_civ.sh -c 8"
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Hi Yadong,
> > > > > > > > > Thanks for your comment.
> > > > > > > > > In this change, we modified the default value of GUEST_CPU_NUM variable in start_civ.sh.
> > > > > > > > > We checked the performance of GeekBench with CIV on CometLake-S target with single instance of CIV. We observed more than 4x performance gain in multi-core score with "-smp 6,cores=3,threads=2,sockets=1" than "-smp 1".
> > > > > > > > > After 6 cores, the performance scaling is not much and hence, we are setting default smp value as 6 cores.
> > > > > > > > > Yes, we modified only default value and user can set value with command argument as well.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Thanks. is there any performance difference between "-smp 6" and "-smp 6,cores=3,threads=2,sockets=1"?
> > > > > > > 
> > > > > > > 
> > > > > > > I followed below link for smp configuration.
> > > > > > > https://manpages.debian.org/testing/qemu-system-x86/qemu-system-x86_64.1.en.html
> > > > > > > As such, I checked with "-smp 6,cores=3,threads=2,sockets=1" and "-smp cores=3,threads=2".
> > > > > > > The “/proc/cpuinfo” shows same number of logical cores for both above configurations.
> > > > > > > And, Geekbench score was same.
> > > > > > 
> > > > > > 
> > > > > > Since it is virtual cpu, so I think no need to specify cores/threads. Please just use "-smp 6". And this config is special for CML-S, maybe "-smp 2" is better as the script is for general case.
> > > > > 
> > > > > 
> > > > > "smp" total value stands for total logical cores which is output of "cores * threads * sockets".
> > > > > "cores" with smp means physical cores and "threads" with smp means hardware threads.
> > > > > I went through few links. Specifying "cores" and "threads" avoid any confusion and is recommended for better performance.
> > > > > We checked on CML-U as well. Performance is scaling more till 6 cores.
> > > > > Do you have any data to prove config with "cores" and "threads" would gain better performance than just config "-smp 6"?
> > > 
> > > 
> > > Below links discuss about mentioning "threads" and "cores" with "smp" with hyper threaded cores.
> > > https://lists.gnu.org/archive/html/qemu-discuss/2014-12/msg00037.html
> > > https://topic.alibabacloud.com/a/kvm-virtualization-smp-symmetric-multi-processor-introduction-and-configuration_8_8_31256740.html
> > 
> > 
> > Cannot find any evidence from these two articals to prove "threads" adn "cores" could improve performances.
> 
> As per one link (discussion in qemu community), do not specify HT in the guest, unless you have HT in
> the host. We have HT enabled with CML target, hence I specified "threads=2" with smp.
> I checked the GeekBench performance with "-smp 6" on CML-S target (with WW44).
> The multi-core score with "-smp 6" is almost half of multi-score with "-smp 6,cores=3,threads=2,sockets=1".
> 
> I was not expecting that much difference.
> So, I rechecked again with "-smp 6,cores=3,threads=2,sockets=1" with same environment.
> The multi-core score with "-smp 6,cores=3,threads=2,sockets=1" is same as earlier.

It is wired, recently, I checked the GeekBench scores on CML-NUL, the result is really different from you. What I got is: "-smp 8" got same result vs "-smp 8,cores=4,threads=2". I will check with you later.

**Review by YadongQi — APPROVED** [review]

**Review by YadongQi — CHANGES_REQUESTED** [review]
why there are 2 commits? please make sure there are only one commit since you have only one new change.

**Pull request closed without merging**
